name: Update VERSION file

on:
  push:
      branches: [main]

jobs:
  update_version:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update VERSION file
        run: |
          make update-version